# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bRFXTbZLPQD58c11niEcIIr3sQZXPgLo
"""

import requests
#import os
from datetime import datetime

api_key = '87d845b0b6cf29baa1a73cc34b067a95'
location = input("Enter the city name: ")

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print (".......................................................")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("........................................................")

print ("Current Temperature is: {:.2f} deg C".format(temp_city))
print ("Current Weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current Wind Speed    :",wind_spd ,'kmph')

with open('output_example.txt','wt') as t:
  t.write("...................................................\n")
  t.write("Weather Stats for - {}  || {}\n".format(location.upper(), date_time))
  t.write("........................................................\n")
  t.write("Current Temperature is: {:.2f} deg C\n".format(temp_city))
  t.write("Current Weather desc  : {}\n".format(weather_desc))
  t.write("Current Humidity      : {}\n".format(hmdt, '%'))
  t.write("Current Wind Speed    : {}\n".format(wind_spd ,'kmph'))